### PR TITLE
added buttons to docs

### PR DESCRIPTION
**Pull request by EricSchles**

### CODE REVIEW

**Comment by liorshahverdi** [comment]
I noticed some problems with the PR. I included a docs folder with an images folder within it to hold the button images. See https://github.com/hackingagainstslavery/django-demo-site/pull/6 @EricSchles

**Comment by EricSchles** [comment]
Oh wow!  Thanks so much @liorshahverdi for catching that!  This is definitely better!  However, there is still a problem - the images references were broken by your directory changes.  So I looked at your PR, added those changes locally and then merged them back into this PR.  Also, just a quick note, it is bad practice to do `git add --all`, sorry I told you to do that :)

**Comment by liorshahverdi** [comment]
Hi @EricSchles, I checked out your changes and I noticed something that we'll need to fix - the filepaths provided for the images specify your fork URL. I'm going to merge this in to get the images on the canonical and then we'll update the URLs.

**Comment by EricSchles** [comment]
Thanks! @liorshahverdi I totally didn't know how to resolve that, having a path forward is great!  I'm going to close out https://github.com/hackingagainstslavery/django-demo-site/pull/6 since it's resolved here.

**Pull request merged**
